name: coco_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  flutter_markdown_plus: ^1.0.7
  font_awesome_flutter: ^10.12.0
  google_fonts: ^8.0.0
  equatable: ^2.0.8
  image_picker: ^1.2.1
  camera: ^0.11.3
  firebase_core: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: WixMadeforText
      fonts:
        - asset: assets/fonts/WixMadeforText-Regular.ttf
          weight: 400
        - asset: assets/fonts/WixMadeforText-Medium.ttf
          weight: 500
        - asset: assets/fonts/WixMadeforText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WixMadeforText-Bold.ttf
          weight: 700
        - asset: assets/fonts/WixMadeforText-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WixMadeforText-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/WixMadeforText-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/WixMadeforText-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/WixMadeforText-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/WixMadeforText-ExtraBoldItalic.ttf
          weight: 800
          style: italic
